enum Action {
  ALL_SCREENS_RETRIEVED = 'ALL_SCREENS_RETRIEVED',
  ALL_TOURS_RETRIEVED = 'ALL_TOURS_RETRIEVED',
  SCREEN_AND_DATA_LOADED = 'SCREEN_AND_DATA_LOADED',
  TOUR = 'TOUR',
  TOUR_AND_DATA_LOADED = 'TOUR_AND_DATA_LOADED',
  GENERIC_LOADING = 'GENERIC_LOADING',
  INIT = 'INIT',
}

export default Action;
