enum Action {
  ALL_SCREENS_LOADING = 'ALL_SCREENS_LOADING',
  ALL_SCREENS_LOADED = 'ALL_SCREENS_LOADED',
  ALL_TOURS_LOADING = 'ALL_TOURS_LOADING',
  ALL_TOURS_LOADED = 'ALL_TOURS_LOADED',
  SCREEN_LOADING = 'SCREEN_LOADING',
  CLEAR_CURRENT_SCREEN = 'CLEAR_CURRENT_SCREEN',
  SCREEN_AND_DATA_LOADED = 'SCREEN_AND_DATA_LOADED',
  TOUR = 'TOUR',
  SCREEN = 'SCREEN',
  TOUR_AND_DATA_LOADED = 'TOUR_AND_DATA_LOADED',
  SAVE_EDIT_CHUNKS = 'SAVE_EDIT_CHUNKS',
  SAVE_TOUR_ENTITIES = 'SAVE_TOUR_ENTITIES',
  GENERIC_LOADING = 'GENERIC_LOADING',
  INIT = 'INIT',
}

export default Action;
