export interface IPriceDetails {
  id: number;
  planName: string;
  planId: 'solo' | 'startup' | 'business' | 'enterprise' | 'lifetime';
  priceAnnual?: number;
  priceMonthly?: number;
  priceLifetime?: number;
  featTitle: string;
  featList: Array<{ id: number; feat: string; isHightlighted: boolean }>;
  buttonText?: string;
  buttonLink?: string;
}

export const PriceDetailsData: Array<IPriceDetails> = [
  {
    id: 1,
    planName: 'Solo',
    planId: 'solo',
    priceAnnual: 0,
    priceMonthly: 0,
    featTitle: "What's included?",
    featList: [
      { id: 1.1, feat: 'Full html capture + edit', isHightlighted: true },
      { id: 1.2, feat: '1 published demo', isHightlighted: false },
      { id: 1.3, feat: 'Unlimited demo views', isHightlighted: false },
      { id: 1.4, feat: '1 creator', isHightlighted: true },
      { id: 1.5, feat: 'Unlimited views and viewers', isHightlighted: false },
      { id: 1.6, feat: 'Share as link or embed', isHightlighted: true },
      { id: 1.7, feat: 'Auto-stitch of demos', isHightlighted: false },
      { id: 1.8, feat: 'Basic Analytics', isHightlighted: false },
    ],
  },
  {
    id: 2,
    planName: 'Startup',
    planId: 'startup',
    priceAnnual: 40,
    priceMonthly: 50,
    featTitle: 'Everything in Solo +',
    featList: [
      { id: 1.2, feat: 'Unlimited demos', isHightlighted: false },
      { id: 1.6, feat: 'Auto-stitch of demo flows', isHightlighted: true },
      { id: 1.3, feat: 'Multi-flow demos with modules', isHightlighted: false },
      { id: 1.4, feat: 'Figma support', isHightlighted: true },
      { id: 1.5, feat: 'Custom webhooks', isHightlighted: false },
      { id: 1.7, feat: 'Call-to-action buttons', isHightlighted: false }
    ],
  },
  {
    id: 3,
    planName: 'Business',
    planId: 'business',
    priceAnnual: 100,
    priceMonthly: 125,
    featTitle: 'Everything in Startup +',
    featList: [
      { id: 2.2, feat: 'Custom lead forms', isHightlighted: true },
      { id: 2.2, feat: 'Personalize demo', isHightlighted: true },
      { id: 2.2, feat: 'Hubspot Integration', isHightlighted: true },
      { id: 2.3, feat: 'Advanced lead level analytics', isHightlighted: true },
      { id: 2.5, feat: 'Advanced branching demo', isHightlighted: false },
      { id: 2.6, feat: 'Audio & video guides', isHightlighted: false },
      { id: 2.7, feat: 'Demo templates', isHightlighted: false },
      { id: 2.8, feat: 'Share demo with select group', isHightlighted: false },
      { id: 2.9, feat: 'Branded landing page for demo', isHightlighted: false },
      { id: 2.11, feat: 'Dedicated support', isHightlighted: false },
    ],
  },
  {
    id: 4,
    planName: 'Enterprise',
    planId: 'enterprise',
    featTitle: 'Everything in Business +',
    featList: [
      { id: 3.2, feat: 'Multi-team', isHightlighted: false },
      { id: 3.3, feat: 'Custom pricing', isHightlighted: false },
      { id: 3.4, feat: 'SSO', isHightlighted: true },
      { id: 3.4, feat: 'Salesforce Integration', isHightlighted: true },
      { id: 3.5, feat: 'Dedicated slack support', isHightlighted: false },
      { id: 3.6, feat: 'Demo coaching', isHightlighted: false },
      { id: 3.7, feat: 'Quarterly demo reviews', isHightlighted: false },
      { id: 3.8, feat: 'Custom APIs', isHightlighted: false },
      { id: 3.9, feat: 'Dedicated CSM', isHightlighted: false },
      { id: 3.11, feat: 'Custom integrations', isHightlighted: false },
    ],
    buttonText: 'Contact Sales',
    buttonLink: 'mailto:vikas@sharefable.com?subject=Enterprise%20plan%20of%20Fable'
  },
];

export const LifetimePriceDetailsData: Array<IPriceDetails> = [
  {
    id: 1,
    planName: 'Tier 1',
    planId: 'lifetime',
    featTitle: '',
    priceLifetime: 49,
    featList: [
      { id: 1.0, feat: '1 creator(s)', isHightlighted: false },
      { id: 1.1, feat: '1 custom domain(s)', isHightlighted: false },
      { id: 1.2, feat: 'Call-to-action buttons', isHightlighted: false },
      { id: 1.3, feat: 'Customize demo loader', isHightlighted: false },
      { id: 1.4, feat: 'No limits on embed', isHightlighted: false },
      { id: 1.5, feat: '60 total mins of audio / video guides', isHightlighted: false },
      { id: 1.6, feat: 'No limit on audio / video streaming', isHightlighted: false },
      { id: 1.7, feat: 'Unlimited published demos', isHightlighted: false },
      { id: 1.8, feat: 'Unlimited demos, views, and viewers', isHightlighted: false },
      { id: 1.9, feat: 'Custom branding', isHightlighted: false },
      { id: 1.1, feat: 'Share as link or embed', isHightlighted: false },
      { id: 1.11, feat: 'Enable hotspot', isHightlighted: false },
      { id: 1.12, feat: 'Basic analytics', isHightlighted: false },
      { id: 1.13, feat: 'Auto-stitch of demo workflows', isHightlighted: false },
      { id: 1.14, feat: 'Text and image in annotation message', isHightlighted: false },
      { id: 1.15, feat: 'Figma support', isHightlighted: false },
      { id: 1.16, feat: 'Custom webhooks', isHightlighted: false },
      { id: 1.17, feat: 'No watermark', isHightlighted: false }
    ],
    buttonText: 'Contact Sales',
    buttonLink: 'mailto:vikas@sharefable.com?subject=Enterprise%20plan%20of%20Fable'
  },
  {
    id: 2,
    planName: 'Tier 2',
    planId: 'lifetime',
    priceLifetime: 119,
    featTitle: '',
    featList: [
      { id: 2, feat: '3 creator(s)', isHightlighted: false },
      { id: 2.1, feat: '3 custom domain(s)', isHightlighted: false },
      { id: 2.2, feat: 'Call-to-action buttons', isHightlighted: false },
      { id: 2.3, feat: 'Customize demo loader', isHightlighted: false },
      { id: 2.4, feat: 'No limits on embed', isHightlighted: false },
      { id: 2.5, feat: '180 total mins of audio / video guides', isHightlighted: false },
      { id: 2.6, feat: 'No limit on audio / video streaming', isHightlighted: false },
      { id: 2.7, feat: 'Multi-flow demos with modules', isHightlighted: false },
      { id: 2.8, feat: 'Blur and hide elements', isHightlighted: false },
      { id: 2.9, feat: 'Zapier integration', isHightlighted: false },
      { id: 2.1, feat: 'Unlimited published demos', isHightlighted: false },
      { id: 2.11, feat: 'Unlimited demos, views, and viewers', isHightlighted: false },
      { id: 2.12, feat: 'Custom branding', isHightlighted: false },
      { id: 2.13, feat: 'Share as link or embed', isHightlighted: false },
      { id: 2.14, feat: 'Enable hotspot', isHightlighted: false },
      { id: 2.15, feat: 'Basic analytics', isHightlighted: false },
      { id: 2.16, feat: 'Auto-stitch of demo workflows', isHightlighted: false },
      { id: 2.17, feat: 'Text and image in annotation message', isHightlighted: false },
      { id: 2.18, feat: 'Figma support', isHightlighted: false },
      { id: 2.19, feat: 'Custom webhooks', isHightlighted: false },
      { id: 2.2, feat: 'No watermark', isHightlighted: false }
    ],
    buttonText: 'Contact Sales',
    buttonLink: 'mailto:vikas@sharefable.com?subject=Enterprise%20plan%20of%20Fable'
  },
  {
    id: 3,
    planName: 'Tier 3',
    planId: 'lifetime',
    priceLifetime: 249,
    featTitle: '',
    featList: [
      { id: 3, feat: 'Unlimited creator(s)', isHightlighted: false },
      { id: 3.1, feat: '10 custom domain(s)', isHightlighted: false },
      { id: 3.2, feat: 'Call-to-action buttons', isHightlighted: false },
      { id: 3.3, feat: 'Customize demo loader', isHightlighted: false },
      { id: 3.4, feat: 'No limits on embed', isHightlighted: false },
      { id: 3.5, feat: '600 total mins of audio / video guides', isHightlighted: false },
      { id: 3.6, feat: 'No limit on audio / video streaming', isHightlighted: false },
      { id: 3.7, feat: 'Multi-flow demos with modules', isHightlighted: false },
      { id: 3.8, feat: 'Blur and hide elements', isHightlighted: false },
      { id: 3.9, feat: 'Zapier integration', isHightlighted: false },
      { id: 3.1, feat: 'HubSpot integration', isHightlighted: false },
      { id: 3.11, feat: 'On-screen HTML customization', isHightlighted: false },
      { id: 3.12, feat: 'Custom lead form', isHightlighted: false },
      { id: 3.13, feat: 'Unlimited published demos', isHightlighted: false },
      { id: 3.14, feat: 'Unlimited demos, views, and viewers', isHightlighted: false },
      { id: 3.15, feat: 'Custom branding', isHightlighted: false },
      { id: 3.16, feat: 'Share as link or embed', isHightlighted: false },
      { id: 3.17, feat: 'Enable hotspot', isHightlighted: false },
      { id: 3.18, feat: 'Basic analytics', isHightlighted: false },
      { id: 3.19, feat: 'Auto-stitch of demo workflows', isHightlighted: false },
      { id: 3.2, feat: 'Text and image in annotation message', isHightlighted: false },
      { id: 3.21, feat: 'Figma support', isHightlighted: false },
      { id: 3.22, feat: 'Custom webhooks', isHightlighted: false },
      { id: 3.23, feat: 'No watermark', isHightlighted: false }
    ],
    buttonText: 'Contact Sales',
    buttonLink: 'mailto:vikas@sharefable.com?subject=Enterprise%20plan%20of%20Fable'
  },
  {
    id: 4,
    planName: 'Tier 4',
    planId: 'lifetime',
    priceLifetime: 449,
    featTitle: '',
    featList: [
      { id: 3, feat: 'Unlimited creator(s)', isHightlighted: false },
      { id: 3.1, feat: '25 custom domain(s)', isHightlighted: false },
      { id: 3.2, feat: 'Call-to-action buttons', isHightlighted: false },
      { id: 3.3, feat: 'Customize demo loader', isHightlighted: false },
      { id: 3.4, feat: 'No limits on embed', isHightlighted: false },
      { id: 3.5, feat: '1200 total mins of audio / video guides', isHightlighted: false },
      { id: 3.6, feat: 'No limit on audio / video streaming', isHightlighted: false },
      { id: 3.7, feat: 'Multi-flow demos with modules', isHightlighted: false },
      { id: 3.8, feat: 'Blur and hide elements', isHightlighted: false },
      { id: 3.9, feat: 'Zapier integration', isHightlighted: false },
      { id: 3.1, feat: 'HubSpot integration', isHightlighted: false },
      { id: 3.11, feat: 'On-screen HTML customization', isHightlighted: false },
      { id: 3.12, feat: 'Custom lead form', isHightlighted: false },
      { id: 3.13, feat: 'Unlimited published demos', isHightlighted: false },
      { id: 3.14, feat: 'Unlimited demos, views, and viewers', isHightlighted: false },
      { id: 3.15, feat: 'Custom branding', isHightlighted: false },
      { id: 3.16, feat: 'Share as link or embed', isHightlighted: false },
      { id: 3.17, feat: 'Enable hotspot', isHightlighted: false },
      { id: 3.18, feat: 'Basic analytics', isHightlighted: false },
      { id: 3.19, feat: 'Auto-stitch of demo workflows', isHightlighted: false },
      { id: 3.2, feat: 'Text and image in annotation message', isHightlighted: false },
      { id: 3.21, feat: 'Figma support', isHightlighted: false },
      { id: 3.22, feat: 'Custom webhooks', isHightlighted: false },
      { id: 3.23, feat: 'No watermark', isHightlighted: false }
    ],
    buttonText: 'Contact Sales',
    buttonLink: 'mailto:vikas@sharefable.com?subject=Enterprise%20plan%20of%20Fable'
  },
  {
    id: 5,
    planName: 'Tier 5',
    planId: 'lifetime',
    priceLifetime: 649,
    featTitle: '',
    featList: [
      { id: 3, feat: 'Unlimited creator(s)', isHightlighted: false },
      { id: 3.1, feat: '60 custom domain(s)', isHightlighted: false },
      { id: 3.2, feat: 'Call-to-action buttons', isHightlighted: false },
      { id: 3.3, feat: 'Customize demo loader', isHightlighted: false },
      { id: 3.4, feat: 'No limits on embed', isHightlighted: false },
      { id: 3.5, feat: '3000 total mins of audio / video guides', isHightlighted: false },
      { id: 3.6, feat: 'No limit on audio / video streaming', isHightlighted: false },
      { id: 3.7, feat: 'Multi-flow demos with modules', isHightlighted: false },
      { id: 3.8, feat: 'Blur and hide elements', isHightlighted: false },
      { id: 3.9, feat: 'Zapier integration', isHightlighted: false },
      { id: 3.1, feat: 'HubSpot integration', isHightlighted: false },
      { id: 3.11, feat: 'On-screen HTML customization', isHightlighted: false },
      { id: 3.12, feat: 'Custom lead form', isHightlighted: false },
      { id: 3.13, feat: 'Unlimited published demos', isHightlighted: false },
      { id: 3.14, feat: 'Unlimited demos, views, and viewers', isHightlighted: false },
      { id: 3.15, feat: 'Custom branding', isHightlighted: false },
      { id: 3.16, feat: 'Share as link or embed', isHightlighted: false },
      { id: 3.17, feat: 'Enable hotspot', isHightlighted: false },
      { id: 3.18, feat: 'Basic analytics', isHightlighted: false },
      { id: 3.19, feat: 'Auto-stitch of demo workflows', isHightlighted: false },
      { id: 3.2, feat: 'Text and image in annotation message', isHightlighted: false },
      { id: 3.21, feat: 'Figma support', isHightlighted: false },
      { id: 3.22, feat: 'Custom webhooks', isHightlighted: false },
      { id: 3.23, feat: 'No watermark', isHightlighted: false }
    ],
    buttonText: 'Contact Sales',
    buttonLink: 'mailto:vikas@sharefable.com?subject=Enterprise%20plan%20of%20Fable'
  }
];
