export enum Msg {
  INIT = "fable/INIT",
  INITED = "fable/INITED",
  SCRIPT_INIT = "fable/SCRIPT_INIT",
  SCRIPT_INIT_DATA = "fable/SCRIPT_INIT_DATA",
  ADD_SAMPLE_USER = "fable/ADD_SAMPLE_USER",
  SAVE_SCREEN = "fable/SAVE_SCREEN",
  SERIALIZE_FRAME = "fable/SERIALIZE_FRAME",
  FRAME_SERIALIZED = "fable/FRAME_SERIALIZED",
  START_RECORDING = "fable/START_RECORDING",
  STOP_RECORDING = "fable/STOP_RECORDING",
  DELETE_RECORDING = "fable/DELETE_RECORDING",
  OPEN_LINK_IN_NEW_TAB = "fable/OPEN_LINK_IN_NEW_TAB",
  TAKE_SCREENSHOT = "fable/TAKE_SCREENSHOT",
  CLIENT_CONTENT_INIT = "fable/CLIENT_CONTENT_INIT",
  SAVE_TOUR_DATA = "fable/SAVE_TOUR_DATA",
  SAVE_SCREENS_DATA_IN_EXCHANGE_DIV = "fable/SAVE_SCREENS_DATA",
  SAVE_COOKIES_DATA_IN_EXCHANGE_DIV = "fable/SAVE_COOKIES_DATA",
  SAVE_TOTAL_SCREEN_COUNT_IN_EXCHANGE_DIV = "fable/SAVE_TOTAL_SCREEN_COUNT_IN_EXCHANGE_DIV",
  SAVE_STYLE_DATA = "fable/SAVE_STYLE_DATA"
}

export interface MsgPayload<T> {
  type: Msg;
  data: T;
}
